run:
  skip-dirs:
    - util
    - .*~
    - api/swagger/docs
  skip-files:
    - ".*\\.my\\.go$"
    - _test.go
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gci:
    local-prefixes: github.com/CSU-Apple-Lab/tinyTikTok
  godox:
    keywords:
      - BUG
      - FIXME
      - OPTIMIZE
      - HACK
  goimports:
    local-prefixes: github.com/CSU-Apple-Lab/tinyTikTok
  gomoddirectives:
    replace-local: true
    replace-allow-list:
      - github.com/coreos/etcd
      - google.golang.org/grpc
  gomodguard:
    allowed:
      modules:
        - gorm.io/gorm
        - gorm.io/driver/mysql
      domains: # List of allowed module domains
        - google.golang.org
        - gopkg.in
        - golang.org
        - github.com
        - go.uber.org
    blocked:
      local_replace_directives: false
  lll:
    line-length: 240